### ISSUE TITLE
Where to download Vanilla?

### ISSUE THREAD

**Issue by darkweb2015** [pdefreitas/Laravel-VanillaSSO#5]
Can you please tell me where I need to have Vanilla downloaded?  Should it go into the public folder?

thanks

**Comment by pdefreitas** [comment]
Hello,

You should run your Vanilla installation separately. This works with Vanilla jsConnect SSO which stands for single sign-on (which is a property of access control of multiple related, but independent software systems).

https://vanillaforums.com/features/single-sign-on

Hope I've helped you.
